### ISSUE TITLE
There is not any warning/error when starting the setup process and wifi/bluetooth are disabled

### ISSUE THREAD

**Issue by isabelrios** [mozilla-sensorweb/sensorweb-client#11]
I am not sure if this is a bug or has not been defined yet. But as a user I would expect to be notified if I start the setup process without data connection and/or bluetooth disabled.

**Comment by mcav** [comment]
Per the UX specs, we explicitly ask them to enable bluetooth, but only immediately before it's needed. They do need a data connection, and we'll warn about that when I complete #4.

**Comment by mcav** [comment]
I should add, that there has been some discussion about when the user will be performing each of those steps, so the point at which we warn the user may change when they come out with the next UX revision.
