### ISSUE TITLE
Scanning label shown at the bottom of the app

### ISSUE THREAD

**Issue by isabelrios** [mozilla-sensorweb/sensorweb-client#17]
Not sure why this is shown and if it should appear in all the screens, just wanted to confim with you @mcav and undestand if it has shown and why...Thanks!
![screenshot_2016-11-02-12-07-19](https://cloud.githubusercontent.com/assets/1897507/19926505/30225afc-a0f5-11e6-8648-8a1a43e361cd.png)

**Comment by mcav** [comment]
Yes, this is expected. It's a status bar that shows the status of the phone's connection to the fake sensor (a node app in the `fake-sensor/` directory in this repo). It will likely remain visible for debugging purposes for quite some time.
