### ISSUE TITLE
error TS2304: Cannot find name '....'

### ISSUE THREAD

**Issue by isabelrios** [mozilla-sensorweb/sensorweb-client#3]
This error was not shown last time I tried to generate the build but it is happening now, am I missing something to install or is it a missing dependency @mcav ?

There are many more, but as an example:

_ERROR in /Users/irios/git/sensorWeb/test/sensorweb-client/node_modules/@types/react/index.d.ts
(2479,36): error TS2304: Cannot find name 'HTMLVideoElement'.

ERROR in /Users/irios/git/sensorWeb/test/sensorweb-client/node_modules/@types/react/index.d.ts
(2480,34): error TS2304: Cannot find name 'HTMLElement'.

ERROR in ./src/ui/index.tsx
(80,7): error TS2304: Cannot find name 'setTimeout'.

ERROR in ./src/ui/index.tsx
(90,7): error TS2304: Cannot find name 'setTimeout'.

ERROR in ./src/state/NavigationState.tsx
(60,5): error TS2304: Cannot find name 'console'._

At the end the build is correctly generated and installed but wondering about the cause of this error and how to fix it.

Thanks!

**Comment by mcav** [comment]
I hadn't yet tested this on a clean install, so I was missing a configuration option. I pushed a new fix on latest master, let me know if that resolved the issue. (Still looking into the WifiWizard problem.)

**Comment by isabelrios** [comment]
Great! no more errors like those. Thanks!
