### ISSUE TITLE
iOS - Field for typing the floor is partially hidden by the keyboard

### ISSUE THREAD

**Issue by isabelrios** [mozilla-sensorweb/sensorweb-client#7]
Please see screenshot below:
![img_0028](https://cloud.githubusercontent.com/assets/1897507/19469702/b87929d8-951c-11e6-8d37-baecece881e5.PNG)

**Comment by mcav** [comment]
Commit [472029](https://github.com/mozilla-sensorweb/sensorweb-client/commit/47202960f7dc059bc6b9c358454c94c5169b9139) addresses this, both for Android and iOS (both input issues were related/identical). Typing in input fields should now look like this, with the header floating on top:

![screen shot 2016-10-18 at 11 11 28 am](https://cloud.githubusercontent.com/assets/42708/19490464/1a3bfd56-9524-11e6-96e9-b7cb704180b8.png)

I've tested manually on both Android and iOS; please reopen if this is still a problem. Thanks!
