### ISSUE TITLE
Android - Password field for connecting to a WiFi is hidden by the keyboard

### ISSUE THREAD

**Issue by isabelrios** [mozilla-sensorweb/sensorweb-client#8]
Please see screenshot:
![screenshot_2016-10-18-10-13-35](https://cloud.githubusercontent.com/assets/1897507/19469764/f112d046-951c-11e6-93b9-8187226f1327.png)

The Connect to Wi-Fi screen is correctly shown but when tapping on the password field the keyboard comes up hidding the password field. Once user types the first characther then the screen scrolls up showing the field completely. Would it be possible to do that scroll once user taps on the field, and not to wait to insert the first character?

**Comment by mcav** [comment]
Addressed by the same fix for #7; see comments there.

**Comment by isabelrios** [comment]
This has been solved, but there have been some side effects on android builds. 
Now tapping on entering the address an the floor scrolls the screen too and seems that too much and the screens are not very nice presented from an user point of view:

![screenshot_2016-10-19-09-39-22](https://cloud.githubusercontent.com/assets/1897507/19510308/f4d5800e-95e2-11e6-96b2-c624a8a38244.png)

![screenshot_2016-10-19-09-39-45](https://cloud.githubusercontent.com/assets/1897507/19510314/fa636720-95e2-11e6-80b9-96e00182705d.png)

Please let me know if you prefer to reopen this issue or open a new one with the side effects found.
Thanks! @mcav

**Comment by mcav** [comment]
What android version is that? I didn't see those same effects on the phones
I tested, so there must be some other variable at play.

**Comment by mcav** [comment]
Actually, I just tested it on my Nexus 4 and am seeing the same flawed result you are. I'd still like to know the version of your phone, but I might be able to reproduce this myself as well.

**Comment by mcav** [comment]
@isabelrios Could you pull the latest master and see if the problem is fixed? And also, the version of android you're testing with?

**Comment by isabelrios** [comment]
Yeah, it seems to be fixed in latest master b7c69859,.
My android device is Sony Z3 with 5.1.1.

There is still one situation in which the Password field is not scrolled.
-Follow the setup process
-Tap Next on Floor selection
-On Connect to Wi-Fi screen tap quickly on Network Name field to get the list of networks
-Close the list of networks screen
-Once you are back to the Connect to Wi-Wi screen, tap on password field

In that case, the screen does not scroll, but this would be less critical since the steps to follow are not the regular ones.

**Comment by mcav** [comment]
What a good catch! I was able to reproduce that also, and discovered the cause: When the "connect to WiFi" list is still dismissing and you tap on the password field, we tried to calculate page height of that modal dialog rather than the page with the password on it.

I've pushed a fix that addresses that issue on my Nexus 4 / 5.1.1; could you check when you have time and also confirm?

**Comment by isabelrios** [comment]
I cannot reproduce this anymore, closing this issue :) Thanks!
